import "./styles.css"

export { default as UiMenu } from "./UiMenu.vue"
export { default as UiMenuTrigger } from "./UiMenuTrigger.vue"
export { default as UiMenuContent } from "./UiMenuContent.vue"
export { default as UiMenuItem } from "./UiMenuItem.vue"
export { default as UiMenuLabel } from "./UiMenuLabel.vue"
export { default as UiMenuSeparator } from "./UiMenuSeparator.vue"
export { default as UiSubMenu } from "./UiSubMenu.vue"
export { default as UiSubMenuTrigger } from "./UiSubMenuTrigger.vue"
export { default as UiSubMenuContent } from "./UiSubMenuContent.vue"

export * from "@workspace/menu-core"
export * from "./useMenu"
export * from "./context"
export { useMenuShortcuts, matchesShortcut } from "./useMenuShortcuts"
