allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@affino/datagrid-core@0.6.0'
  - '@affino/datagrid-pivot@0.2.0'
  - '@affino/datagrid-vue-app@0.6.0'
  - '@affino/datagrid-vue@0.6.0'
  - '@affino/datagrid-worker@0.6.0'
  - '@affino/diagram-core@0.2.0 || 0.3.0'
  - '@affino/diagram-vue@0.2.0 || 0.3.0'
  - '@affino/dialog-core@1.3.0'
  - '@affino/dialog-vue@1.3.0'
  - '@affino/menu-core@1.2.0'
  - '@affino/menu-vue@2.2.0'
  - '@affino/treeview-core@0.3.0'
  - '@affino/treeview-vue@0.3.0'
