services:
  api:
    # Переопределяем команду, добавляя --reload для "горячей" перезагрузки
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

    # Примонтируем локальный код, чтобы изменения сразу были видны
    volumes:
      - ./backend/app:/app/app

    # Прокинем порт наружу, если хотим обращаться к FastAPI напрямую
    # (Например, http://localhost:8000/docs )
    ports:
      - "8000:8000"

  adminer:
    image: adminer
    container_name: fat-simulator-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy

  # (Опционально) Поменять настройку nginx:
  # может захотим другой порт для dev, чтоб не конфликтовать с системой.
  nginx:
    ports:
      - "8080:80"