services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      tags:
        - unitlab-dev:latest
    container_name: unitlab-dev-container
    volumes:
      - .:/workspace
    command: sleep infinity
    networks:
      - net
  db:
    image: postgres:16
    container_name: unitlab-db-dev
    restart: unless-stopped
    env_file:
      - ./backend/.env.db.dev
    ports:
      - "5433:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    networks:
      - net

  redis:
    image: redis:7
    container_name: unitlab-redis-dev
    tmpfs:
      - /data
    ports:
      - "6379:6379"
    networks:
      - net

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: unitlab-mosquitto-dev
    ports:
      - "1883:1883"
    tmpfs:
      - /mosquitto/data
      - /mosquitto/log
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - net

volumes:
  db_data_dev:

networks:
  net:
