services:
  db:
    image: postgres:latest
    container_name: unitlab-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network
  
  adminer:
    image: adminer
    container_name: unitlab-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - db

  nginx:
    image: nginx:latest  # или build: ./nginx если используем Dockerfile
    container_name: unitlab-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      # Монтируем нашу собранную статику (dist) в html-папку Nginx:
      - ../frontend/dist:/usr/share/nginx/html
      # Монтируем конфиг Nginx (см. nginx.conf ниже)
      - ../config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network: