import { palette, toRgb, toRgba, transparent } from "../theme"
import type { UiTableStyleConfig } from "./types"

// TODO(theme): move preset definitions into src/ui-table/theme to keep core layer style-free.

export const industrialNeutralTheme: UiTableStyleConfig = {
  inheritThemeFromDocument: true,
  defaultTokenVariant: "light",
  tokenVariants: {
    light: {
      tableFontFamily:
        '"IBM Plex Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
      tableFontSize: "0.75rem",
      tableTextColor: toRgb(palette.slate800),
      tableBackgroundColor: toRgb(palette.white),
      headerBackgroundColor: toRgb(palette.gray150),
      headerTextColor: toRgb(palette.zinc600),
      headerBorderColor: toRgb(palette.gray200),
      headerPaddingX: "0.75rem",
      headerPaddingY: "0.5rem",
      bodyRowBackgroundColor: toRgb(palette.white),
      bodyRowTextColor: toRgb(palette.slate800),
      bodyRowHoverBackgroundColor: toRgba(palette.blue500, 0.08),
      bodyRowSelectedBackgroundColor: toRgba(palette.blue500, 0.18),
      bodyRowSelectedTextColor: toRgb(palette.slate800),
      bodyCellPaddingX: "0.75rem",
      bodyCellPaddingY: "0.375rem",
      bodyCellBorderColor: toRgb(palette.gray200),
      selectionCellBackgroundColor: toRgb(palette.gray150),
      selectionCellTextColor: toRgb(palette.slate800),
      indexCellBackgroundColor: toRgb(palette.gray150),
      indexCellTextColor: toRgb(palette.slate500),
      rowDividerSize: "1px",
      rowDividerColor: toRgb(palette.gray200),
      columnDividerSize: "1px",
      columnDividerColor: toRgb(palette.gray200),
      headerDividerSize: "1px",
      headerDividerColor: toRgb(palette.gray200),
      summaryDividerSize: "1px",
      summaryDividerColor: toRgb(palette.gray200),
      groupRowBackgroundColor: toRgba(palette.gray150, 0.85),
      groupRowTextColor: toRgb(palette.zinc600),
      summaryRowBackgroundColor: toRgb(palette.gray150),
      summaryRowTextColor: toRgb(palette.slate600),
      summaryLabelTextColor: toRgb(palette.slate500),
      pinnedBackgroundColor: toRgb(palette.gray50),
      pinnedLeftBackgroundColor: toRgb(palette.gray50),
      pinnedRightBackgroundColor: toRgb(palette.gray50),
      pinnedShadow: `0 0 0 0 ${transparent()}`,
      pinnedLeftShadow: `inset -1px 0 0 ${toRgba(palette.slate400, 0.35)}`,
      pinnedRightShadow: `inset 1px 0 0 ${toRgba(palette.slate400, 0.35)}`,
      pinnedLeftBorderColor: toRgb(palette.slate400),
      pinnedLeftBorderWidth: "1px",
      pinnedRightBorderColor: toRgb(palette.slate400),
      pinnedRightBorderWidth: "1px",
    },
    dark: {
      tableFontFamily:
        '"IBM Plex Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
      tableFontSize: "0.75rem",
      tableTextColor: toRgb(palette.gray200),
      tableBackgroundColor: toRgb(palette.slate900),
      headerBackgroundColor: toRgb(palette.slate800),
      headerTextColor: toRgb(palette.gray200),
      headerBorderColor: toRgb(palette.slate700),
      headerPaddingX: "0.75rem",
      headerPaddingY: "0.5rem",
      bodyRowBackgroundColor: toRgb(palette.slate900),
      bodyRowTextColor: toRgb(palette.gray200),
      bodyRowHoverBackgroundColor: toRgba(palette.blue400, 0.16),
      bodyRowSelectedBackgroundColor: toRgba(palette.blue400, 0.32),
      bodyRowSelectedTextColor: toRgb(palette.gray50),
      bodyCellPaddingX: "0.75rem",
      bodyCellPaddingY: "0.375rem",
      bodyCellBorderColor: toRgb(palette.slate800),
      selectionCellBackgroundColor: toRgb(palette.slate800),
      selectionCellTextColor: toRgb(palette.gray50),
      indexCellBackgroundColor: toRgb(palette.slate800),
      indexCellTextColor: toRgb(palette.gray400),
      rowDividerSize: "1px",
      rowDividerColor: toRgb(palette.slate800),
      columnDividerSize: "1px",
      columnDividerColor: toRgb(palette.slate800),
      headerDividerSize: "1px",
      headerDividerColor: toRgb(palette.slate700),
      summaryDividerSize: "1px",
      summaryDividerColor: toRgb(palette.slate800),
      groupRowBackgroundColor: toRgba(palette.slate800, 0.9),
      groupRowTextColor: toRgb(palette.gray300),
      summaryRowBackgroundColor: toRgb(palette.slate800),
      summaryRowTextColor: toRgb(palette.gray100),
      summaryLabelTextColor: toRgb(palette.gray400),
      pinnedBackgroundColor: toRgb(palette.slate900),
      pinnedLeftBackgroundColor: toRgb(palette.slate850),
      pinnedRightBackgroundColor: toRgb(palette.slate850),
      pinnedShadow: `0 0 0 0 ${transparent()}`,
      pinnedLeftShadow: `inset -1px 0 0 ${toRgba(palette.slate500, 0.45)}`,
      pinnedRightShadow: `inset 1px 0 0 ${toRgba(palette.slate500, 0.45)}`,
      pinnedLeftBorderColor: toRgb(palette.slate500),
      pinnedLeftBorderWidth: "1px",
      pinnedRightBorderColor: toRgb(palette.slate500),
      pinnedRightBorderWidth: "1px",
    },
  },
  body: {
    row: "selectable-row selectable-row--idle",
  },
  state: {
    selectedRow: "selectable-row selectable-row--selected",
  },

}
