import type { UiTableThemeTokens } from "./types"

export const defaultThemeTokens: UiTableThemeTokens = {
  tableFontFamily:
    '"IBM Plex Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  tableFontSize: "0.75rem",
  tableTextColor: "#1f2937",
  tableBackgroundColor: "#ffffff",
  headerBackgroundColor: "#f3f4f6",
  headerTextColor: "#4b5563",
  headerBorderColor: "#d1d5db",
  headerPaddingX: "0.75rem",
  headerPaddingY: "0.5rem",
  headerHighlightBorderColor: "#3b82f6",
  headerHighlightTextColor: "#1f2937",
  headerSelectedTextColor: "#1f2937",
  headerSystemTextColor: "#1f2937",
  bodyRowBackgroundColor: "#ffffff",
  bodyRowTextColor: "#1f2937",
  bodyRowHoverBackgroundColor: "rgba(59, 130, 246, 0.08)",
  bodyRowSelectedBackgroundColor: "rgba(59, 130, 246, 0.18)",
  bodyRowSelectedTextColor: "#1f2937",
  bodyCellPaddingX: "0.75rem",
  bodyCellPaddingY: "0.375rem",
  bodyCellBorderColor: "#d1d5db",
  selectionCellBackgroundColor: "#f3f4f6",
  selectionCellTextColor: "#1f2937",
  indexCellBackgroundColor: "#f3f4f6",
  indexCellTextColor: "#6b7280",
  rowDividerSize: "1px",
  rowDividerColor: "#e5e7eb",
  columnDividerSize: "1px",
  columnDividerColor: "#e5e7eb",
  headerDividerSize: "1px",
  headerDividerColor: "#d1d5db",
  summaryDividerSize: "1px",
  summaryDividerColor: "#e5e7eb",
  groupRowBackgroundColor: "rgba(243, 244, 246, 0.85)",
  groupRowTextColor: "#4b5563",
  summaryRowBackgroundColor: "#f3f4f6",
  summaryRowTextColor: "#4b5563",
  summaryLabelTextColor: "#6b7280",
  pinnedBackgroundColor: "#f9fafb",
  pinnedLeftBackgroundColor: "#f9fafb",
  pinnedRightBackgroundColor: "#f9fafb",
  pinnedShadow: "0 0 0 0 rgba(0, 0, 0, 0)",
  pinnedLeftShadow: "inset -1px 0 0 rgba(148, 163, 184, 0.35)",
  pinnedRightShadow: "inset 1px 0 0 rgba(148, 163, 184, 0.35)",
  pinnedLeftBorderColor: "#94a3b8",
  pinnedLeftBorderWidth: "1px",
  pinnedRightBorderColor: "#94a3b8",
  pinnedRightBorderWidth: "1px",
}
