// src/ui-table/theme/tokens.ts
// Defines the mapping between logical tokens and CSS custom properties.

import type { UiTableThemeTokens } from "./types"

export const THEME_TOKEN_VARIABLE_MAP: Record<keyof UiTableThemeTokens, string> = {
  tableFontFamily: "--ui-table-font-family",
  tableFontSize: "--ui-table-font-size",
  tableTextColor: "--ui-table-text-color",
  tableBackgroundColor: "--ui-table-background-color",
  headerBackgroundColor: "--ui-table-header-background-color",
  headerTextColor: "--ui-table-header-text-color",
  headerBorderColor: "--ui-table-header-border-color",
  headerPaddingX: "--ui-table-header-padding-x",
  headerPaddingY: "--ui-table-header-padding-y",
  headerHighlightBorderColor: "--ui-table-header-highlight-border-color",
  headerHighlightTextColor: "--ui-table-header-highlight-text-color",
  headerSelectedTextColor: "--ui-table-header-selected-text-color",
  headerSystemTextColor: "--ui-table-header-system-text-color",
  bodyRowBackgroundColor: "--ui-table-row-background-color",
  bodyRowTextColor: "--ui-table-row-text-color",
  bodyRowHoverBackgroundColor: "--ui-table-row-hover-background-color",
  bodyRowSelectedBackgroundColor: "--ui-table-row-selected-background-color",
  bodyRowSelectedTextColor: "--ui-table-row-selected-text-color",
  bodyCellPaddingX: "--ui-table-body-cell-padding-x",
  bodyCellPaddingY: "--ui-table-body-cell-padding-y",
  bodyCellBorderColor: "--ui-table-cell-border-color",
  selectionCellBackgroundColor: "--ui-table-selection-cell-background-color",
  selectionCellTextColor: "--ui-table-selection-cell-text-color",
  indexCellBackgroundColor: "--ui-table-index-cell-background-color",
  indexCellTextColor: "--ui-table-index-cell-text-color",
  rowDividerSize: "--ui-table-row-divider-size",
  rowDividerColor: "--ui-table-row-divider-color",
  columnDividerSize: "--ui-table-column-divider-size",
  columnDividerColor: "--ui-table-column-divider-color",
  headerDividerSize: "--ui-table-header-divider-size",
  headerDividerColor: "--ui-table-header-divider-color",
  summaryDividerSize: "--ui-table-summary-divider-size",
  summaryDividerColor: "--ui-table-summary-divider-color",
  groupRowBackgroundColor: "--ui-table-group-row-background-color",
  groupRowTextColor: "--ui-table-group-row-text-color",
  summaryRowBackgroundColor: "--ui-table-summary-row-background-color",
  summaryRowTextColor: "--ui-table-summary-row-text-color",
  summaryLabelTextColor: "--ui-table-summary-label-text-color",
  pinnedBackgroundColor: "--ui-table-pinned-bg",
  pinnedLeftBackgroundColor: "--ui-table-pinned-left-bg",
  pinnedRightBackgroundColor: "--ui-table-pinned-right-bg",
  pinnedShadow: "--ui-table-pinned-shadow",
  pinnedLeftShadow: "--ui-table-pinned-left-shadow",
  pinnedRightShadow: "--ui-table-pinned-right-shadow",
  pinnedLeftBorderColor: "--ui-table-pinned-left-border-color",
  pinnedLeftBorderWidth: "--ui-table-pinned-left-border-width",
  pinnedRightBorderColor: "--ui-table-pinned-right-border-color",
  pinnedRightBorderWidth: "--ui-table-pinned-right-border-width",
}
