per_listener_settings true
listener 1883 0.0.0.0
allow_anonymous false
password_file /mosquitto/config/passwordfile
acl_file /mosquitto/config/aclfile
persistence true
persistence_location /mosquitto/data/
log_type all
log_dest stdout
