server {
    listen 80;
    server_name _;

    # Указываем корень - смонтированную папку /usr/share/nginx/html (где dist)
    root /usr/share/nginx/html;
    index index.html;

    # Если вы хотите, чтобы все пути, кроме /api, отдавались фронтовым index.html
    # (Single Page App fallback):
    location / {
        add_header Cache-Control "no-cache, no-store, must-revalidate" always;
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        add_header Cache-Control "public, max-age=31536000, immutable" always;
        try_files $uri =404;
    }

    location /api/ {
        proxy_pass http://unitlab-backend:8000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect off;
    }

    location /openapi.json {
        proxy_pass http://unitlab-backend:8000/openapi.json;
    }
    location /docs {
        proxy_pass http://unitlab-backend:8000/docs;
    }

    location /ws/ {
        proxy_pass http://unitlab-backend:8000/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 86400;
        proxy_buffering off;
    }
}
