"""create devices table

Revision ID: 0a4b81b85a02
Revises: 
Create Date: 2025-04-25 14:57:08.143000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4b81b85a02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'devices',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('unit_id', sa.String(), unique=True, index=True, nullable=False),
        sa.Column('type', sa.String(), nullable=True),
        sa.Column('channels', sa.Integer(), nullable=True),
        sa.Column('firmware_version', sa.String(), nullable=True),
        sa.Column('location', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), default=True, nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_unit_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
