"""dev init

Revision ID: 55cb4ecb6cd2
Revises: 
Create Date: 2025-12-04 12:13:47.427179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55cb4ecb6cd2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('num_channels', sa.Integer(), nullable=True),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_devices_last_seen_at', 'devices', ['last_seen_at'], unique=False)
    op.create_index('ix_devices_type_unit', 'devices', ['device_type', 'unit_id'], unique=False)
    op.create_index(op.f('ix_devices_unit_id'), 'devices', ['unit_id'], unique=True)
    op.create_table('sequences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel_index', sa.Integer(), nullable=False),
    sa.Column('channel_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'channel_index', name='uq_channels_device_index')
    )
    op.create_index('ix_channels_device_id', 'channels', ['device_id'], unique=False)
    op.create_table('sequence_steps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sequence_id', sa.BigInteger(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('switchgears',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('do_open', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('do_closed', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('di_open', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('di_close', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('feedback_delay_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['di_close'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['di_open'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['do_closed'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['do_open'], ['channels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('switchgears')
    op.drop_table('sequence_steps')
    op.drop_index('ix_channels_device_id', table_name='channels')
    op.drop_table('channels')
    op.drop_table('sequences')
    op.drop_index(op.f('ix_devices_unit_id'), table_name='devices')
    op.drop_index('ix_devices_type_unit', table_name='devices')
    op.drop_index('ix_devices_last_seen_at', table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
