server {
    listen 80;

    # Указываем корень - смонтированную папку /usr/share/nginx/html (где dist)
    root /usr/share/nginx/html;
    index index.html;

    # Если вы хотите, чтобы все пути, кроме /api, отдавались фронтовым index.html
    # (Single Page App fallback):
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Проксируем API-запросы к FastAPI:
    location /api/ {
        proxy_pass http://host.docker.internal:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_redirect off;
        proxy_set_header Accept application/json;
    }

}
